### ISSUE TITLE
PReLU and ELU was not add to the list into isinstance

### ISSUE THREAD

**Issue by gdshen** [Swall0w/torchstat#2]
PReLU and ELU was not add to the list into isinstance
https://github.com/Swall0w/torchstat/blob/621549e458971e12eb70a118fc8a7d9b0247abfd/torchstat/compute_flops.py#L61

although they are added in 
https://github.com/Swall0w/torchstat/blob/621549e458971e12eb70a118fc8a7d9b0247abfd/torchstat/compute_flops.py#L13

**Comment by Swall0w** [comment]
Thank you for the information. I've fixed it :thumbsup:
