### ISSUE TITLE
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by saysth** [Swall0w/torchstat#22]
solved

**Comment by supratikbanerjee** [comment]
how?

**Comment by saysth** [comment]
`device = torch.device("cpu")
model = model.to(device)
stat(model, (3, 224, 224))`

**Comment by supratikbanerjee** [comment]
oh... so for cpu it's solved... and not cuda?

**Comment by supratikbanerjee** [comment]
model_hook.py
ln 22: x = torch.rand(1, *self._input_size).to('cuda')
ln 47: itemsize = input[0].cpu().detach().numpy().itemsize

did this... seems to be working for cuda now.

**Comment by saysth** [comment]
i think it doesn't matter for cpu or cuda. you could load model to cpu just for calculating, it won't affect your training on cuda.

**Comment by chumingqian** [comment]
Hi, @saysth :
    I use the cpu ,and got the following error,   could you help me take a look, thanks

  #  compute Flops ,parameters
    print("/n the following present is Flops, parameters: /n")
    device = torch.device("cpu")
    model = model.to(device)
    stat(model, (3,416,416))


 File "/home/respecting-god/Github/yolov3v4-modelCompression/models.py", line 497, in forward_once
    yolo_out.append(module(x, out))
  File "/home/respecting-god/anaconda3/envs/torch1.7.0/lib/python3.8/site-packages/torchstat/model_hook.py", line 58, in wrap_call
    np.array(output.size()[1:], dtype=np.int32))
AttributeError: 'tuple' object has no attribute 'size'

**Comment by OpenAI-chn** [comment]
> Hi, @saysth : I use the cpu ,and got the following error, could you help me take a look, thanks
> # compute Flops ,parameters
> 
> ```
> print("/n the following present is Flops, parameters: /n")
> device = torch.device("cpu")
> model = model.to(device)
> stat(model, (3,416,416))
> ```
> 
> File "/home/respecting-god/Github/yolov3v4-modelCompression/models.py", line 497, in forward_once yolo_out.append(module(x, out)) File "/home/respecting-god/anaconda3/envs/torch1.7.0/lib/python3.8/site-packages/torchstat/model_hook.py", line 58, in wrap_call np.array(output.size()[1:], dtype=np.int32)) AttributeError: 'tuple' object has no attribute 'size'

我也遇到这个问题了
