### ISSUE TITLE
AttributeError: 'torch.Size' object has no attribute 'numel'

### ISSUE THREAD

**Issue by Hansoluo** [Swall0w/torchstat#6]
When I use it to test my net, it reports an error:
`File "/torchstat/compute_memory.py", line 57, in compute_Conv2d_memory
    mread = batch_size * (inp.size()[1:].numel() + num_params(module))
AttributeError: 'torch.Size' object has no attribute 'numel'
`

And I found in pytorch documents [torch.numel](https://pytorch.org/docs/stable/torch.html?highlight=numel#torch.numel) , only tensor have the attribute 'numel'. So, I have no idea How can I get this to work.If anyone can help, thanks.

I use python 3.5  Pytorch 0.4.1.

**Comment by yaotc** [comment]
the same error .

**Comment by lyakaap** [comment]
I fixed this problem. See https://github.com/Swall0w/torchstat/pull/8

**Comment by woaichipinngguo** [comment]
I encountered the error again. @Hansoluo @Swall0w

**Comment by Hansoluo** [comment]
@woaichipinngguo   @yaotc I used this file [compute_memory.py](https://github.com/lyakaap/torchstat/blob/master/torchstat/compute_memory.py) to replace original `compute_memory.py`. And it worked for me. @lyakaap, Thanks for your help.

**Comment by woaichipinngguo** [comment]
ConvTranspose2d and Upsample are not supported. @Hansoluo

**Comment by yaotc** [comment]
> compute_memory.py

@Hansoluo   @lyakaap  Thank you all ~ It worked!

**Comment by Hansoluo** [comment]
@woaichipinngguo  "Upsample"  layer have no paraments when inference, so inference memory and Flops is zero. "ConvTranspose2d" maybe you can use this [math equation](https://zhuanlan.zhihu.com/p/39240159) to calculate by hand. Or you can  use it as same as "Conv2d", just add this layer in script.
```
def compute_memory(module, inp, out):
    ...
    elif isinstance(module, nn.ConvTranspose2d):
         return compute_Conv2d_memory(module, inp, out)
    ....
```

**Comment by xiaoketongxue** [comment]
I used this file compute_memory.py to replace original compute_memory.py. 
but
  File "D:\Anaconda3\lib\site-packages\torchstat\compute_memory.py", line 57, in compute_Conv2d_memory
    mwrite = out.numel()

AttributeError: 'torch.Size' object has no attribute 'numel'
This is why?
